### ISSUE TITLE
Remove serve dependency

### ISSUE THREAD

**Issue by thephilgray** [joeblethephilgray/svelte-playground#9]
Package not necessary for this epic. Should remove until ready to discuss deployment methods.

**Comment by knoebelja** [comment]
Well, I don't mind trying out now in the future. I think it's fine to leave in if you agree. We can remove it when we make a hard decision, since it was part of the template we chose. If you already think using now is a bad idea though, let's remove it.

**Comment by thephilgray** [comment]
@knoebelja, I don't think using `now` is a bad idea, but I think it makes sense to remove it as a dependency for the same reason we agreed to remove it from the `README`. It's safe to assume it was only included in the original template for demonstration. But since we're far from adding a deployment step, it adds extra weight and complexity. If someone were to clone the repo and attempt to use it, it might not work as expected, esp. depending on changes we make to the template. And it's not practical to manually test it each time we do make changes.

**Comment by knoebelja** [comment]
Okay, feel free to remove it in a PR.
